#!/bin/bash

echo "==================================="
echo "GitHub Repository Setup Instructions"
echo "==================================="
echo ""
echo "1. First, go to https://github.com/new and create a new repository named 'silver-fin-monitor'"
echo "   - Do NOT initialize with README, .gitignore, or license"
echo ""
echo "2. After creating the repository, replace YOUR_USERNAME below with your GitHub username:"
echo ""
echo "Run these commands:"
echo ""
echo "git remote add origin https://github.com/YOUR_USERNAME/silver-fin-monitor.git"
echo "git branch -M main"
echo "git push -u origin main"
echo ""
echo "3. After pushing, go to Netlify.com to connect and deploy"
echo ""
echo "==================================="
echo "Current git status:"
echo ""
git status --short
echo ""
echo "Ready to push to GitHub!"