# Netlify Configuration for Silver Fin Monitor

# Build settings
[build]
  # Directory to change to before starting a build
  base = "/"
  
  # Build command - build Netlify function and frontend
  command = "./build.sh"
  
  # Directory that contains the deploy-ready files
  publish = "frontend/dist"
  
  # Directory for serverless functions
  functions = "netlify/functions"
  
  # Port configuration for dev server
  [dev]
    port = 8888
    functionsPort = 8888
    # Enable auto-rebuild for functions during development
    autoLaunch = true
    # Target directory for dev server (Vite dev server)
    targetPort = 5173
    # Auto-detect framework and start both frontend and functions
    framework = "#auto"
    # Enable live reload for functions
    liveReload = true
    # Force TypeScript compilation in dev mode
    force = true

# Development proxy configuration

# Build environment variables
[build.environment]
  NODE_VERSION = "20.11.1"
  NPM_VERSION = "10"

# Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"

# API routes - no caching for dynamic content
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, private"
    Pragma = "no-cache"
    Expires = "0"

# Static assets - no caching
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
    
[[headers]]
  for = "/*.css"  
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# API proxy redirects - all API calls go to the serverless function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = false

# SPA redirect for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variable configuration
[context.production.environment]
  VITE_API_URL = "/api"
  VITE_SUPABASE_URL = "https://pnjtzwqieqcrchhjouaz.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBuanR6d3FpZXFjcmNoaGpvdWF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NjQ3MTksImV4cCI6MjA2ODQ0MDcxOX0.SHaa8zOiHm6rJfmRS2XUQT_Rq_kkyihvL0a4GPGCLPg"

[context.deploy-preview.environment]
  VITE_API_URL = "/api"
  
[context.branch-deploy.environment]
  VITE_API_URL = "/api"

# Function configuration
[functions]
  # Directory for serverless functions
  directory = "netlify/functions"
  
  # Node.js version for functions
  node_bundler = "esbuild"
  
  # esbuild configuration for TypeScript
  [functions.esbuild]
    # Target ES2020 for Node.js compatibility
    target = "es2020"
    # Enable TypeScript support
    loader = { ".ts" = "ts" }
    # External dependencies
    external = ["aws-sdk"]


  [functions."scheduled-feed-processing"]
    schedule = "0 */6 * * *"  # Every 6 hours

  [functions."scheduled-daily-analysis"]
    schedule = "0 6 * * *"    # Daily at 6 AM UTC

# Plugins
[[plugins]]
  package = "@netlify/plugin-functions-install-core"

  